# Generated by Django 3.0.2 on 2021-07-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('time_millisecond', models.CharField(blank=True, max_length=255, verbose_name='API kelgan vaqt (format:millisecond)')),
                ('time_datetime', models.DateTimeField(blank=True, null=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti:')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqti:')),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='Aniqlanmadi!', null=True)),
                ('type', models.IntegerField(choices=[(1, 'Kirim'), (2, "Ariza uchun to'lov"), (4, 'Balansdan yechish')], default=1, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, default='0', help_text='XXX.XX som', max_digits=18, verbose_name='Summa')),
                ('reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tranzaksiya sababi (izoh)')),
                ('state', models.IntegerField(choices=[(0, 'Не существует'), (1, 'Создан'), (2, 'Оплачен'), (-1, 'Отменен'), (-2, 'Отменена после завершения')], default=1)),
                ('balance_updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.TgUser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Транзаксия',
                'verbose_name_plural': 'Транзаксиялар',
            },
        ),
    ]
