# Generated by Django 3.0.2 on 2021-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_balancetransaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
