# Generated by Django 3.0.2 on 2021-07-10 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='Foydalanuvchi ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Foydalanuvchi ismi')),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('tel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqam')),
                ('lan', models.CharField(blank=True, choices=[('oz', "O'zbek"), ('uz', 'Узбек'), ('ru', 'Руский'), ('en', 'Ingliz')], max_length=2, null=True, verbose_name='Foydalanuvchi tili')),
                ('block_count', models.IntegerField(default=0, verbose_name='Bloklanishlar soni')),
                ('step', models.IntegerField(default=0, verbose_name='TEGILMASIN!!!')),
                ('balance', models.IntegerField(default=0, verbose_name='Foydalanuvchi hisobi')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
