# Generated by Django 3.0.2 on 2021-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Blocked'), (3, 'Deleted')], default=1),
        ),
    ]
